language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
  - BUILD_NUMBER=4
  - TABRIS_ANDROID_PLATFORM=${HOME}/tabris-android

before_install:
  - nvm install 6.1
  - npm install -g npm@'^4.3.0'
  - npm install -g grunt-cli
  - npm install -g cordova@6.5.0
  - npm install -g tabris-cli@0.6.0
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
  - npm install

before_script:
  - curl -Lo ${HOME}/tabris-android.zip https://tabrisjs.com/downloads/2.0.0-rc1/platforms/tabris-android.zip
  - unzip -d ${HOME} ${HOME}/tabris-android.zip
  - ls -la ${HOME}
  - ls -la ${HOME}/tabris-android

script: tabris build android
