language: android

jdk:
  - oraclejdk8

env:
  global:
  - BUILD_NUMBER=4

before_install:
  - nvm install 6.1
  - npm install -g npm@'^4.3.0'
  - npm install -g grunt-cli
  - npm install -g tabris-cli@~2.2.0
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
  - npm install

script: tabris build android
